server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8080


rabbitmq:
  host:     localhost
  port:     5672
  username: coffee
  password: coffee
  exchange: orders-exchange
  queue:    orders-queue

cors:
  allowedOrigins:
    - "http://localhost:3000"
  allowedMethods:
    - "GET"
    - "POST"
    - "OPTIONS"
  allowedHeaders:
    - "Content-Type"
    - "Authorization"